### ISSUE TITLE
辅助功能自动关闭

### ISSUE THREAD

**Issue by h2y** [hyb1996/NoRootScriptDroid#197]
每当关闭 autojs 时，app 貌似会自动将已授权的辅助功能给主动关掉。

再未 root 的机器上，第二次打开 app 时又不能自动开启上服务，这样就没法用 tasker 自动运行了。

希望删掉退出 app 时关闭辅助功能的设定。

**Comment by hyb1996** [comment]
这不是app自动关的。而是系统自动关的。解决方法是加入到自启动名单，或者加入杀进程的白名单，以及不杀死app的后台。

**Comment by h2y** [comment]
谢谢解答，测试了下确实是系统的原因。

**Comment by h2y** [comment]
对了，在没有开启辅助功能的情况下，运行脚本会失败。

在脚本开头有写 "auto"，但是由于设备未 root，此句没有任何用。

我认为在未 root 设备下，APP 应当弹出请求激活的对话框（就像第一次运行那样），并且在用户手动激活后继续运行接下来的程序。
