### ISSUE TITLE
源码无法编译

### ISSUE THREAD

**Issue by Specher** [hyb1996/NoRootScriptDroid#198]
六一快乐，源码无法编译

**Comment by Specher** [comment]
额 没初始化完毕

**Comment by hyb1996** [comment]
哪里没法编译？

**Comment by Specher** [comment]
你设置了127.0.0.1:1080代理
gradle.properties 里面代理服务器去掉就行了

**Comment by Specher** [comment]
我build提示
D:\ASPROJ\NoRootScriptDroid-master\autojs\src\main\java\com\stardust\autojs\rhino_android\AndroidContextFactory.java
Error:(25, 79) 错误: 程序包com.faendir.rhino_android不存在

D:\ASPROJ\NoRootScriptDroid-master\autojs\src\main\java\com\stardust\autojs\engine\NodeJsJavaScriptEngine.java
Error:(3, 23) 错误: 程序包com.iwebpp.node不存在

现在提示这两个没找到 
我在APP的 build.gradle 的dependency里加入
compile 'com.faendir.rhino:rhino-android:1.4' 和
compile 'com.github.hyb1996:node-android-lib:1.0.14'
然后Rebulid
他又提示
Error:Execution failed for task ':app:mergeDebugResources'.
> [drawable/side_menu_bg] D:\ASPROJ\NoRootScriptDroid-master\app\src\main\res\drawable\side_menu_bg.png	[drawable/side_menu_bg] D:\ASPROJ\NoRootScriptDroid-master\app\src\main\res\drawable\side_menu_bg.webp: Error: Duplicate resources

我把side_menu_bg.webp这个文件重命名
再Build
终于成功拉！

**Comment by hyb1996** [comment]
话说这两个应该已经被移除了吧。NodeJsJavaScriptEngine和rhino android部分应该都被删掉了。

**Comment by Specher** [comment]
额，可能是我下载源码直接替换的问题，还有一个小BUG，如果是从我的脚本切换到任务管理 还是没有正在运行的脚本那几个字还在 要刷新才会没 还有就是建议不能同时运行相同脚本

**Comment by Specher** [comment]
幸苦了 早点睡啊 么么哒
