### ISSUE TITLE
I

### ISSUE THREAD

**Issue by oi0i0io** [hyb1996/NoRootScriptDroid#201]
I

-

Device info:
---
<table>
<tr><td>App version</td><td>1.17.0221</td></tr>
<tr><td>App version code</td><td>31</td></tr>
<tr><td>Android build version</td><td>1489459235</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>alps-mp-m0.mp1-V2.84_tinno6737t.65.m0_P147</td></tr>
<tr><td>Device brand</td><td>BLU</td></tr>
<tr><td>Device manufacturer</td><td>BLU</td></tr>
<tr><td>Device name</td><td>R1_PLUS</td></tr>
<tr><td>Device model</td><td>R1 PLUS</td></tr>
<tr><td>Device product name</td><td>R1_PLUS</td></tr>
<tr><td>Device hardware name</td><td>mt6735</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by hyb1996** [comment]
???
