### ISSUE TITLE
有在未来加入将脚本打包成apk的功能的打算吗？

### ISSUE THREAD

**Issue by Yidadaa** [hyb1996/NoRootScriptDroid#205]
如果可以将脚本打包成apk，以后就可以用js写原生app了，想起来就美滋滋。
（作为一个前端，实在控制不了用js写一切东西的欲望啊……）

另外仓库里好像没有提供多少文档，希望作者能把文档补充下。

**Comment by hyb1996** [comment]
打包功能已经初步试验成功了。未来会加上的。但是考虑到加入打包功能会大大减少用户量（大多数用户只用其中一个脚本，因此会选择打包成apk后卸载AutoJs）。所以会等脚本社区开发后再加上这个功能。

**Comment by hyb1996** [comment]
文档确实很少...暑假慢慢补上吧~

**Comment by Yidadaa** [comment]
好吧，确实会有用户量的问题。
其实我很期待着能用这个写app😀

**Comment by hyb1996** [comment]
在提交9077e49中已经加入了该功能
