### ISSUE TITLE
关于动作录制精度过高的问题

### ISSUE THREAD

**Issue by chenjau** [hyb1996/NoRootScriptDroid#213]
由于手指操作上的精确度问题, 录制的时候会产生大量冗余的动作, 比如
```
sh.Touch(416, 1152);
sh.SendEvent(0, 0, 0);
sh.Touch(421, 1148);
sh.SendEvent(0, 0, 0);
sh.Touch(426, 1144);
sh.SendEvent(3, 48, 5);
sh.SendEvent(0, 0, 0);
sh.Touch(432, 1140);
sh.SendEvent(0, 0, 0);
```
以上捕捉到多个动作, 其实仅为点击一个按钮. 坐标之间仅差几个像素点, 对于触摸来说, 应该忽略.
建议捕捉到一个动作后, 屏蔽该点位周围 N 像素, 会否好些?

**Comment by hyb1996** [comment]
录制的一个目标就是完美回放（虽然现在只能做到接近完美录制但无法完美回放），因此会保留所有动作；但代码的精简可以做到，比如`sh.Touch(432, 1140);sh.SendEvent(0, 0, 0);`简化为`sh.TouchSync(432, 1140);`。
保留动作对于游戏之类的录制是比较重要的~

**Comment by chenjau** [comment]
但如果一个1080宽度的手机, 几个像素的偏差毛算算只有千分之几的cm. 应该不会导致误差吧? 感觉代价挺高的.

**Comment by hyb1996** [comment]
#221 最新版已经改用了二进制的录制格式，能做到比较完美的回放了。文件大小问题已经不是关键了（可以通过改进二进制文件格式尽量压缩，目测压缩可以达到1/10）。另外用最新版录制游戏也发现了必须把所有动作记录下来否则差别很大。
