### ISSUE TITLE
关于动作录制拖拉动作的效率的问题 

### ISSUE THREAD

**Issue by chenjau** [hyb1996/NoRootScriptDroid#214]
目前的版本(2.0.14 beta)下, 动作录制中的拖拉/拖放动作会产生大量的SendEvent, Touch, TouchX, TouchY 动作. 加上 #213 问题的影响, 情况较为严重, 一个十几个动作(包含3到4个拖放动作)的录制, 生成的脚本高达2800行, 体积达到60kb. 运行的时候遇到拖放动作, 会卡死.
建议录制中对于拖拉动作使用gesture(N, [x,y], [x1, y1]). 可以极大缩减生成的代码量, 提高运行效率.

**Comment by hyb1996** [comment]
不行，gesture只能在7.0以上系统使用，而录制使用的是root权限，录制出来的也是使用root权限的；目前还不能做到对录制的动作的精确回放，正在尝试能否改进，如果可以，则不会再出现运行时的问题。

**Comment by hyb1996** [comment]
拖放动作产生的脚本确实很大，但是即便用gesture也是很难优化的。手的操作肯定不是一个直线或者简单曲线，不能用gesture把他“优化”为一个直线或简单曲线触摸，这样处理在有精细要求的录制中很容易出问题的。

**Comment by chenjau** [comment]
如果gesture有兼容问题的话, 我觉得减少采样点也是个办法.
很多场合采用 起点 -> 终点是否就够了, 中间的轨迹可以取消和忽略, 如果要监视全轨迹, 就使用采样的方式, 尽量减少轨迹点. 
目前的拖放录制实现, 由于采用了所有点(或者说极多的点), 导致回放的时候会卡死.

**Comment by hyb1996** [comment]
#221 最新版已经改用了二进制的录制格式，回放不再会卡死了。生成的脚本虽然仍然比较大（一个十几秒的拖放动作要20KB），但未来可以通过压缩来优化（直接zip的话可以压缩到4KB）。
