### ISSUE TITLE
关于脚本编辑器打开大文件时卡死的问题

### ISSUE THREAD

**Issue by chenjau** [hyb1996/NoRootScriptDroid#215]
比如 #214 问题中产生的大体积脚本文件, 在编辑器中卡顿, 基本无法实行有效编辑.

**Comment by hyb1996** [comment]
确实，但因为是使用开源编辑器[920文本编辑器](https://github.com/jecelyin/920-text-editor-v2)，很难在我这个层面上提高编辑器对大文件的支持；对于此类大文件只能用QuickEdit之类的编辑。

**Comment by hyb1996** [comment]
#221 最新版已经改用了二进制的录制格式，生成的文件不可编辑。

**Comment by hyb1996** [comment]
#239 已经使用了基于CodeMirror的新编辑器，一般文件不会有卡顿问题了（亲测4MB不卡）
