### ISSUE TITLE
能否增加插入注释的机制?

### ISSUE THREAD

**Issue by chenjau** [hyb1996/NoRootScriptDroid#216]
对于录制出的中长脚本来说, 由于没有注释, 导致很难判断脚本中的流程和逻辑, 建议在悬浮按钮中增加一个添加注释功能, 那么在录制过程中, 可以适时插入注释, 对于脚本的 debug 和长期维护应该很有帮助.

**Comment by hyb1996** [comment]
注释指的是什么嘞？能否举个例子？

**Comment by chenjau** [comment]
就是普通的js注释, 比如说:

开始录制

添加注释: // 按A按钮
进行按A按钮动作

添加注释: // 拖拉B控件
进行拖拉B控件动作.
.
.
.

最终生成的脚本类似
// 按A按钮
Touch(399, 532);
SendEvent(3, 48, 4);
// 拖拉B控件
gesture(...)
.
.
.

如此, 生成的脚本具有可读性, 也方便进行改进和调整. 
如果没有注释, 各个动作之间, 完全靠 sleep 区分, 特别对于很长的脚本, 极难修改和维护.

**Comment by hyb1996** [comment]
#221 最新版已经改用了二进制的录制格式，注释机制不再考虑增加。可以分段录制。
