### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by adymilk** [hyb1996/NoRootScriptDroid#218]
Could not GET 'https://jcenter.bintray.com/com/getkeepsafe/dexcount/dexcount-gradle-plugin/0.6.4/dexcount-gradle-plugin-0.6.4.pom
请问这个什么原因呢？

**Comment by hyb1996** [comment]
虽然已经在QQ上回复了，不过还是说一下让后面的人可以参考。
应该是代理设置问题，项目根目录的gradle.properties设置了http和https代理，可以尝试把这几行去掉，或者开启地址为127.0.0.1端口为1080的VPN。

**Comment by a309371807** [comment]
用什么工具可以开启127.0.0.1端口为1080的VPN。
