### ISSUE TITLE
请问有在线的api文档不？

### ISSUE THREAD

**Issue by jy1989** [hyb1996/NoRootScriptDroid#222]
建议可以弄一个web版本的文档和例子，手机里看实在太难看了。

**Comment by hyb1996** [comment]
文档是用markdown写的，可以直接在github上看：https://github.com/hyb1996/NoRootScriptDroid/tree/master/app/src/main/assets/help/documentation

**Comment by hyb1996** [comment]
文档已转移为Node.js类似的在线文档，参见[Auto.js-Docs](https://github.com/hyb1996/AutoJs-Docs)。
