### ISSUE TITLE
请问一下如何获取手机系统时间

### ISSUE THREAD

**Issue by 7huo** [hyb1996/NoRootScriptDroid#223]
JavaScript好像不行

**Comment by hyb1996** [comment]
[Date](http://www.w3school.com.cn/jsref/jsref_obj_date.asp)

**Comment by 7huo** [comment]
谢谢

**Comment by msnlcl** [comment]
如果需要获得北京时间，可以考虑从腾讯的平台通过网络接口直接获取！
