### ISSUE TITLE
导入问题 mac

### ISSUE THREAD

**Issue by parks1234** [hyb1996/NoRootScriptDroid#226]
Error:A problem occurred configuring root project 'NoRootScriptDroid-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.4.
     Required by:
         project :
      > Could not resolve com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.4.
         > Could not get resource 'https://jcenter.bintray.com/com/getkeepsafe/dexcount/dexcount-gradle-plugin/0.6.4/dexcount-gradle-plugin-0.6.4.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/getkeepsafe/dexcount/dexcount-gradle-plugin/0.6.4/dexcount-gradle-plugin-0.6.4.pom'.
               > Connect to 127.0.0.1:1080 [/127.0.0.1] failed: Connection refused

**Comment by parks1234** [comment]
我换成最新的7.3也不行

**Comment by parks1234** [comment]
Gradle 'NoRootScriptDroid-master' project refresh failed

**Comment by hyb1996** [comment]
代理问题，在[gradle.properties](https://github.com/hyb1996/NoRootScriptDroid/blob/master/gradle.properties)文件去掉代理设置。

**Comment by parks1234** [comment]
你设置代理？

**Comment by parks1234** [comment]
我猜到是网络问题了 我以为我这网络出问题了

**Comment by parks1234** [comment]
你代理为什么写俩边 有什么特殊要求么

**Comment by parks1234** [comment]
方法数的这个插件好用么 我用的不是这个插件

**Comment by hyb1996** [comment]
代理是http和https。
方法数的插件可以直接去掉。其实我也很少用。

**Comment by parks1234** [comment]
一般在你请求的时候不就写一种http么

**Comment by hyb1996** [comment]
一些依赖要https才行。像上面的插件就是https下载的。不过我不确定不开代理能不能正常下载，我都是习惯开着的

**Comment by parks1234** [comment]
你这个代理是本地ip吧

**Comment by parks1234** [comment]
本地端口1080 本地IP127.0.0。1

**Comment by parks1234** [comment]
去掉后ok了

**Comment by hyb1996** [comment]
是的，就是本地开一个ss

**Comment by parks1234** [comment]
进去后进入 inrt页面一片空白。

**Comment by parks1234** [comment]
AutoJs 这个类在哪里

**Comment by parks1234** [comment]
AutoJs.getInstance().getScriptEngineService().execute(source);
初始化语句换掉了么

**Comment by parks1234** [comment]
不对啊 运行后没有按流程走 我看到清单文件的入口断电没反应

**Comment by parks1234** [comment]
文件类的后缀都加_不知道为啥

**Comment by parks1234** [comment]
SplashActivity.intent(getActivity())
                                    .extra(SplashActivity.NOT_START_MAIN_ACTIVITY, true)
                                    .extra(SplashActivity.FORCE_SHOW_AD, true)
                                    .start();
这种internt 报错

**Comment by parks1234** [comment]
我是缺什么配置文件了么

**Comment by hyb1996** [comment]
后缀加下划线是对的不用改，这是android annoations框架自动生成的文件，去掉就不能用了。

**Comment by hyb1996** [comment]
inrt模块是indenpent runtime，是试验打包为独立app的。试验过了就删了代码留着模块以后再写。

**Comment by parks1234** [comment]
Error:(30, 1) 错误: The AndroidManifest.xml file contains the original component, and not the AndroidAnnotations generated component. Please register TaskerScriptEditActivity_ instead of TaskerScriptEditActivity

**Comment by parks1234** [comment]
跑步起来的

**Comment by parks1234** [comment]
Error:(27, 1) 错误: The AndroidManifest.xml file contains the original component, and not the AndroidAnnotations generated component. Please register TaskPrefEditActivity_ instead of TaskPrefEditActivity

**Comment by parks1234** [comment]
我删了从来一次

**Comment by parks1234** [comment]
这下行了之前是哪里动错地方了吧

**Comment by hyb1996** [comment]
嗯 另外如果要最新版最好切换到dev分支
