### ISSUE TITLE
对于某些控件无法点击是否有比root多点触摸更好的解决办法

### ISSUE THREAD

**Issue by zhangzhengyi12** [hyb1996/NoRootScriptDroid#230]
我在尝试写一个MIUI商店自动领取红包的脚本，但因为MIUI商店的大部分按钮都是clickable=false的，无法点击，

**Comment by hyb1996** [comment]
如果控件是不能点击的，可能他的父控件或者子控件可以点击
如果也不行，一种相对兼容但是需要root权限或者安卓7.0+的方法是，获取到这个控件，通过bounds属性获取到其坐标，再点击
例如:
```
var btn = className("TextView").findOne();
var b  = btn.bounds();
click(b.centerX(), b.centerY());//或者Tap等
```

**Comment by zhangzhengyi12** [comment]
我确实再试这个方法，但是遇到了一个问题，即无法真正tap, 使用RootAuto显示这个函数未定义，而Tap函数没有作用，

另外就是你例子中的删除全部空间留言，在没有修改的情况下是有效tap的，但当我删除最后的while循环（其他部分没有更改），前面的几个Tap居然无法生效了，这让我非常奇怪，找不到问题出在哪

**Comment by zhangzhengyi12** [comment]
后续：已经解决，问题出在Tap应该是异步，进EventLoop的 。后续代码太少就直接结束执行脚本了，所以Tap并不会后续执行，每次Tap后睡300秒即可

**Comment by craftsman-li** [comment]
相对兼容但是需要root权限或者安卓7.0+的方法:: root权限是怎么个开法？？能安装app的时候就开吗？

**Comment by hyb1996** [comment]
@craftsman-li root权限用Tap或者RootAutomator，Auto.js会自己申请权限
