### ISSUE TITLE
Can not run on Android 4.2.

### ISSUE THREAD

**Issue by qwIvan** [hyb1996/NoRootScriptDroid#234]
![image](https://user-images.githubusercontent.com/7613160/30521907-35b38242-9bfa-11e7-9082-43f007f523d7.png)

**Comment by hyb1996** [comment]
本身脚本编辑器用的是 920文本编辑器，他不支持Android4.2，所以这个问题除非更换编辑器否则很难解决。
另外Android 4.2所支持的无障碍很有限。

**Comment by qwIvan** [comment]
所以我其实可以在5.1的设备上把文件编辑好调试好，再放进4.2中执行，无需打开编辑器？

**Comment by hyb1996** [comment]
是的；但要注意4.2上一些函数用不了，比如输入文本

**Comment by hyb1996** [comment]
#239 已经使用了基于CodeMirror的新编辑器，支持安卓4.2。可以在交流群下载内测版使用。
