### ISSUE TITLE
使用体验反馈

### ISSUE THREAD

**Issue by javaeryang** [hyb1996/NoRootScriptDroid#241]
打开了悬浮窗以后，安装一些应用，安装包管理器那个界面，点不了安装按钮，提示被遮挡，把悬浮窗拖到X里面，才会关闭悬浮窗，这个操作不人性化，关闭悬浮窗才能点安装包。仅供参考。

**Comment by hyb1996** [comment]
悬浮窗已经在#240 中改为新悬浮窗，这个悬浮窗不再有该问题
