### ISSUE TITLE
新版的RootAutomator需要什么权限

### ISSUE THREAD

**Issue by 7huo** [hyb1996/NoRootScriptDroid#244]
360N4S手机root后，开启辅助，测试RootAutomator的示例无法点击。

旧的Tap可以点击，感觉延迟半秒。

是不是RootAutomator需要什么权限，谢谢。

**Comment by hyb1996** [comment]
可以检查软件数据目录（/data/data/com.stardust.scriptdroid/）下的cache/root_automator文件是否存在，权限是否为777或755，录制的文件是否大于256字节。
如果这些都没问题的话，试试用终端模拟器运行命令：
先运行getevent命令，随意触摸屏幕，可以看到有/dev/input/event*的输出，记住这个数字，然后运行命令
```
/data/data/com.stardust.scriptdroid/cache/root_automator /sdcard/record.auto -d /dev/input/event1
```
其中/sdcard/record.auto是要运行的文件的路径，而/dev/input/event1后面的数字1可能要刚刚用getevent对应的那个数字。

**Comment by 7huo** [comment]
录制脚本正常代码类似

`sleep(1000);

var ra = new RootAutomator();
ra.setScreenMetrics(1080, 1920);
ra.touchX(676);
ra.touchY(1767);
ra.sendEvent(1, 330, 1);
ra.sendSync();
sleep(73);
ra.sendEvent(3, 57, -1);
ra.sendEvent(1, 330, 0);
ra.sendSync();
ra.exit();`

**Comment by hyb1996** [comment]
如果在设置里选择产生二进制文件，可以运行吗？

**Comment by 7huo** [comment]
二进制的录制也正常，
只有手动写的不行
`sleep(1000);
var ra = new RootAutomator();
ra.setScreenMetrics(1080, 1920);
ra.tap(676, 1767);
ra.tap(100, 100, 1);
ra.exit();

`

**Comment by hyb1996** [comment]
tap可能无法起到点击效果
试试用press

**Comment by 7huo** [comment]
ra.press(668, 1788,9);
可以了，第三个参数要大于等于9
