### ISSUE TITLE
3.0.0 Alpha14 连接电脑无日志输出

### ISSUE THREAD

**Issue by drakeet** [hyb1996/NoRootScriptDroid#247]
这个项目给我带来了许多便捷和帮助，做得特别好，感谢分享与开源！

我在使用 3.0.0 Alpha14 客户端版本结合 Sublime 插件，发现 log 内容不会输出到电脑面板，3.0 之前是正常的。不知道作者有测试过这块内容吗？

**Comment by hyb1996** [comment]
感谢使用~~
这个问题确实是bug, 并在后来的[提交](https://github.com/hyb1996/NoRootScriptDroid/commit/f3ee94b1cf348b5b9f86180b20832b754590ec24)中修复了。可以使用
这个版本：[release-3.0.0 Alpha20.zip](https://github.com/hyb1996/NoRootScriptDroid/files/1445809/release-3.0.0.Alpha20.zip)。
另外如果使用VS Code也可以使用[VS Code插件](https://github.com/hyb1996/Auto.js-VSCode-Extension)。

**Comment by drakeet** [comment]
太好了，谢谢你！
